#!/bin/sh

# Name: 98-custom-sport-route
# Version: 08-jan-2024
# Description: OpenWRT hoptlug script routing a specific sourceport via the WAN
# Usage: When running a concurrent VPN client and VPN server and needing to route the VPN server port via the WAN
# Installation: 
#  in this script below adapt the port you want to route via the WAN to resemble the VPN server port
#  copy script to /etc/hotplug.d/iface

SPORT=1194  # adapt the port number e.g 1194 for OpenVPN 51820 for WireGuard

#DEBUG=; set -x; logger -t hotplug $(env); # uncomment/comment to enable/disable debug mode
TID=100
{
# getdefault gateway
get_gateway() {
		GATEWAY="$(ifstatus wan | grep nexthop | sed 's/[^0-9.]//g')"
}

set_routes() {
	if [ "$INTERFACE" == "lan" ]; then
		if [ "$ACTION" == "ifup" ]; then
			get_gateway
			# add default route via WAN to table
			ip route add default via $GATEWAY table $TID
			echo "default route via $GATEWAY added to table $TID"
			# add local routes can be neabled if needed
			# ip route show | grep -Ev '^default |^0.0.0.0/1 |^128.0.0.0/1 ' | while read route; do
				# ip route add $route table $TID >/dev/null 2>&1
			# done
			# add rule
			ip rule add sport $SPORT table $TID
			echo "rule $SPORT added to table $TID"
		fi
		# remove table and rules
		if [ "$ACTION" == "ifdown" ]; then
			while ip rule delete from 0/0 to 0/0 table $TID >/dev/null 2>&1; do true; done
			ip route flush table $TID
			echo "clean up"
		fi
	fi
}
set_routes
} 2>&1 | logger $([ ${DEBUG+x} ] && echo '-p user.debug') \
    -t $(echo $(basename $0) | grep -Eo '^.{0,23}')[$$] &
