#!/bin/sh
# Table number
TABLE=101

#DEBUG=; set -x;  # uncomment/comment to enable/disable debug mode 
{
# Start script cleaning up
ip route flush table $TABLE >/dev/null 2>&1
while ip rule delete from 0/0 to 0/0 table $TABLE >/dev/null 2>&1; do true; done
# restart routing optional
service network restart
} 2>&1 | logger $([ ${DEBUG+x} ] && echo '-p user.debug') \
    -t $(echo $(basename $0) | grep -Eo '^.{0,23}')[$$] &
