#!/bin/sh
# Table number
TABLE=101

# Start script cleaning up
ip route flush table $TABLE >/dev/null 2>&1
while ip rule delete from 0/0 to 0/0 table $TABLE >/dev/null 2>&1; do true; done
# restart routing optional
#service network restart
