#!/bin/sh
# set clients ip addresses to route via the VPN, use CIDR notation, change to your need
IPSOURCE="192.168.1.64/26"

# Interface used by the OpenVPN tunnel, usually tun0, trying to get it from environment with $dev
[[ -z "$dev" ]] && TUN="tun0" || TUN="$dev"
#logger -t egc "$(echo $(basename $0)) uses interface:[$dev] = $TUN"

# Table number
TABLE=101

# Start script add default route to table
ip route add default via $route_vpn_gateway dev $TUN table $TABLE
# Add local routes
ip route show | grep -Ev '^default |^0.0.0.0/1 |^128.0.0.0/1 ' | while read route; do
    ip route add $route table $TABLE >/dev/null 2>&1
done
# Add rules, you can add more rules with e.g.: interface:iif, sourceport:sport etc., see ip rule man page
ip rule add from $IPSOURCE table $TABLE  
# examples
# ip rule add iif br-guest table $TABLE  


