#!/bin/sh
# File name: ovpn-update-resolv-7
# Description: Script to grab DNS servers from the tunnel for exclusive use by DNSMasq and routes those via the tunnel to prevent DNS leaks
# Version: 22-jan-2024
# Before you start make a backup of your settings just in case
# Install:
#  Copy this cript to /etc/openvpn
#  Make executable: chmod +x /etc/openvpn/ovpn-update-resolv-7
#  Add in the OpenVPN config file these two lines:
#   up /etc/openvpn/ovpn-update-resolv-7
#   down /etc/openvpn/ovpn-update-resolv-7
##   script-security 2 #not necessary is already taken care of
# Fundamentals:
#  Gets the pushed DNS servers and DNS servers manually set in conf file with: dhcp-option DNS <ip-address-of-DNS-server>
#  DNS servers are set in a new resolv file which is used exclusively by DNSMasq to prevent DNS leaks.
#  Sets route for the DNS servers via the tunnel, necessary when using PBR
#  To stop getting the pushed DNS servers by the OpenVPN server add to conf file: pull-filter ignore "dhcp-option DNS"
#     but if you add this setting then you must add your own DNS servers otherwise you will not have DNS!
#  To set your own DNS servers to use when the tunnel is up, add in the openvpn conf file: dhcp-option DNS ip-address-DNS-server
#  To set your own search domain to use when the tunnel is up, add in the openvpn conf file: dhcp-option DOMAIN my-search-domain
#  When something goes wrong, disable the VPN and restore DNS with: `uci del dhcp.@dnsmasq[0].resolvfile && uci commit dhcp` , and reboot

# https://openwrt.org/docs/guide-user/services/vpn/openvpn/extras#network_interface 

#set -x
(
VPN_RESOLVF="/tmp/resolv_conf.vpn"
DEF_RESOLVF="/tmp/default_resolv_ovpn"
[[ "${-/x/}" != "$-" ]] && env > /tmp/vpn_env_var_up #for debug to get all environment variables
case $script_type in
up)
	# if $DEF_RESOLVF exists when the tunnel is brought up it indicates a dirty ifdown so reset to defaults
	[[ "$VPN_RESOLVF" = "$(uci get dhcp.@dnsmasq[0].resolvfile)" ]] && { uci set dhcp.@dnsmasq[0].resolvfile="/tmp/resolv.conf.d/resolv.conf.auto"; \
		 rm -fr "$DEF_RESOLVF" >/dev/null 2>&1; uci commit dhcp; logger -t $(basename $0)[$$] -p user.notice "Dirty ifdown detected reset DNSMasq to default"; }

	# Get DNS servers and DNS servers manually set in conf file
	rm -fr "$VPN_RESOLVF" >/dev/null 2>&1
	env | grep 'dhcp-option DNS' | awk '{ print "nameserver " $3 }' > $VPN_RESOLVF
	env | grep 'dhcp-option DOMAIN' | awk '{ print "search " $3 }' >> $VPN_RESOLVF
	if ! grep -q 'nameserver' "$VPN_RESOLVF"; then
		logger -t $(basename $0)[$$] -p user.warning "No openvpn DNS servers found, using default servers!"
		rm -fr "$VPN_RESOLVF" >/dev/null 2>&1
		return 0
	fi
	# Make sure DNS servers are always routed via the tunnel e.g. in case of PBR
	if [[ -s $VPN_RESOLVF ]]; then
		while read dns; do
			ip route add $(echo $dns | awk '{print $2}') dev $dev
		done < $VPN_RESOLVF  | grep 'nameserver'
	fi
	# Save default resolv file
	uci get dhcp.@dnsmasq[0].resolvfile > $DEF_RESOLVF
	# Replace default resolv file
	uci set dhcp.@dnsmasq[0].resolvfile=$VPN_RESOLVF
	#uci commit dhcp
	/etc/init.d/dnsmasq restart &
	logger -t $(basename $0)[$$] -p user.notice "Exclusively using openvpn DNS server(s) from $VPN_RESOLVF"
	;;
down)
	# Restore dns, deleting the resolv file path will use default
	if [[ -s $DEF_RESOLVF ]]; then
		uci set dhcp.@dnsmasq[0].resolvfile=$(cat $DEF_RESOLVF)
	elif [[ -e $DEF_RESOLVF ]]; then
		uci del dhcp.@dnsmasq[0].resolvfile
	else	#no DNS servers present so did not run
		logger -t $(basename $0)[$$] -p user.notice "No openvpn DNS server(s) set so nothing to do on ifdown"
		return 0
	fi
	# Instead of removing the resolv file consider: uci set dhcp.@dnsmasq[0].resolvfile="/tmp/resolv.conf.d/resolv.conf.auto" 
	#uci commit dhcp
	/etc/init.d/dnsmasq restart &
	# Remove routing of DNS servers, often redundant as the routes are removed anyway if the interface disappears
	if [[ -s $VPN_RESOLVF ]]; then
	while read dns; do
		ip route del $(echo $dns | awk '{print $2}') dev $dev >/dev/null 2>&1
	done < $VPN_RESOLVF  | grep 'nameserver'
	fi
	# Remove vpn resolv file
	rm -fr "$VPN_RESOLVF" >/dev/null 2>&1
	rm -fr "$DEF_RESOLVF" >/dev/null 2>&1
	logger -t $(basename $0)[$$] -p user.notice "Default DNS server(s) restored"
	;;
esac
exit 0
) 2>&1 | logger -t $(basename $0)[$$] &
